import Head from 'next/head'
import Login from '../../components/logins/Login'

export default function ParentLogin() {
  return (
    <div>
      <Head>
        <title>Login - Parent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login type="parent"/>
    </div>
  )
}
