import Head from 'next/head'
import Login from '../../components/logins/Login'

export default function StudentLogin() {
  return (
    <div>
      <Head>
        <title>Login - Student</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login type="student"/>
    </div>
  )
}
