import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import { useAuth } from '../authContext'
import Dashboard from '../components/Dashboard'

export default function DashboardPage() {

  const router = useRouter()

  const {user, setUser} = useAuth()

  useEffect(() => {
    
    if(localStorage.length == 0 && !user){
      router.push('/login')
    } else if(localStorage.getItem("token")){
      for(const item in localStorage) {
        setUser({...user, [item]: localStorage.getItem(item)})
      }
    }

  }, [])
  
  if(!user){
    return
  }

  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard/>
    </div>
  )
}
