import Head from 'next/head'
import Image from 'next/image'
import Login from '../components/Login'

export default function LoginPage() {
  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Login/>
      
    </div>
  )
}
